apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: workqueue
deploy:
  kubectl:
    manifests:
    - deploy/microservices/redis.yaml

profiles:
- name: minikube
  activation:
    - kubeContext: minikube
  deploy:
    kubectl:
      manifests:
      - deploy/microservices/redis-local.yaml

- name: production
  activation:
    - kubeContext: nlp-ingestion-production
  deploy:
    kubectl:
      manifests:
      - deploy/microservices/redis-vpc.yaml