# This initialises the redis work queue
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-workqueue
spec:
  template:
    spec:
      containers:
      - name: init-workqueue
        image: nlp-ingestion-worker
        args: [ 'setup.py' ]
        volumeMounts:
          - name: configs
            mountPath: res/configs/
            readOnly: true
          - name: db-creds
            mountPath: res/db-creds/
            readOnly: true
      volumes:
        - name: configs
          configMap:
            name: configs
            items:
            - key: base-configs
              path: base_configs.yaml
            - key: newsfilter-configs
              path: newsfilter_configs.yaml
            - key: reddit-configs
              path: reddit_configs.yaml
            - key: setup-configs
              path: setup_configs.yaml
        - name: db-creds
          secret:
            secretName: db-creds
            items:
            - key: scraper-storage
              path: scraper_storage.yaml
            - key: big-universe
              path: big_universe.yaml
      restartPolicy: Never
