---
apiVersion: v1
kind: Secret
metadata:
  name: db-creds
type: Opaque
data:
  scraper-storage: c2VydmljZV90eXBlOiBtb25nbwpjcmVkZW50aWFsczoKICBob3N0OiBtb25nb2RiOi8vYWRtaW46cmVzZWFyY2gyMUBlYzc2OGFhMy1iYjk3LTQyMWMtOThiZC00ODIyZmE3ZGJlYTEtMC5iODI2NzgzMTk1NWY0MGVmOGZiNTUzMGQyODBlNWExMC5kYXRhYmFzZXMuYXBwZG9tYWluLmNsb3VkOjMyNDgxLGVjNzY4YWEzLWJiOTctNDIxYy05OGJkLTQ4MjJmYTdkYmVhMS0xLmI4MjY3ODMxOTU1ZjQwZWY4ZmI1NTMwZDI4MGU1YTEwLmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWQ6MzI0ODEsZWM3NjhhYTMtYmI5Ny00MjFjLTk4YmQtNDgyMmZhN2RiZWExLTIuYjgyNjc4MzE5NTVmNDBlZjhmYjU1MzBkMjgwZTVhMTAuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZDozMjQ4MS9pYm1jbG91ZGRiP2F1dGhTb3VyY2U9YWRtaW4mcmVwbGljYVNldD1yZXBsc2V0CiAgc3NsX2NhX2NlcnRfcGF0aDogcmVzL2Nsb3VkL21vbmdvX2NhY2VydAogIGRhdGFiYXNlOiBMVVJLRVJTCg==
  big-universe: c2VydmljZV90eXBlOiBwb3N0Z3JlcwpjcmVkZW50aWFsczoKICAgIGhvc3Q6IGRyb2lkLXYyLXByb2QtaW5zdGFuY2UuY3k0ZG9md3RuZmZwLmFwLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQogICAgcG9ydDogNTQzMgogICAgZGJuYW1lOiBwb3N0Z3JlcwogICAgdXNlcjogbmxwX3JlYWRfb25seQogICAgcGFzc3dvcmQ6IHFFOXd5UWhI